# Generate guides with mdBook and publish on GitHub Pages
name: Documentation

on:
  release:
    types: [published]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Generate Guides
  build-guides:
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: 0.5.2
    steps:
      - uses: actions/checkout@v4

      - name: Install mdBook
        run: |
          wget https://github.com/rust-lang/mdBook/releases/download/v${MDBOOK_VERSION}/mdbook-v${MDBOOK_VERSION}-x86_64-unknown-linux-gnu.tar.gz
          tar xzf mdbook-v${MDBOOK_VERSION}-x86_64-unknown-linux-gnu.tar.gz

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with mdBook
        run: ./mdbook build # generates ./book directory

      - name: Upload Guides Raw Material
        uses: actions/upload-artifact@v4
        with:
          name: guides-output
          path: book

  # Generate API References
  build-reference:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/yard.gemfile
    steps:
      - uses: actions/checkout@v4

      # actually, we need only yard gem, not the whole Gemfile.lock
      - name: Setup Ruby & Bundle
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Build API Reference
        run: bundle exec yardoc # generates ./yardoc directory

      - name: Upload Guides Raw Material
        uses: actions/upload-artifact@v4
        with:
          name: reference-output
          path: yardoc

  # Merge and Deploy to GitHub Pages
  deploy:
    needs: [build-guides, build-reference]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Create Unified Deployment Directory
        run: mkdir -p combined-docs

      - name: Download Guides
        uses: actions/download-artifact@v4
        with:
          name: guides-output
          path: combined-docs/guides

      - name: Download API Reference
        uses: actions/download-artifact@v4
        with:
          name: reference-output
          path: combined-docs/reference

      - name: Upload Single Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: combined-docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
